name: IRLTime
main: fr.pelt10.irltime.IRLTime
version: 1.0
author: Pelt10
commands:
  irltime:
     description: You can enable/disable IRLTime with this command !
     permission: irltime.admin
     usage: /<command>